### ISSUE TITLE
GitCheatFinder

### ISSUE THREAD

**Issue by aritra-tech** [aadityamp01/Androapps#100]
**Please describe about your Androapp**
Git Cheat Finder is an Android Application 📲 to easily find the right Git Commands that you want to use. It is made using Kotlin and REST API

**Describe alternatives you've considered**
No alternatives are present.

**Additional context**
![182035975-f56345de-6fe7-4047-9a22-375d55690048](https://user-images.githubusercontent.com/80090908/194641876-110a03d9-bc8a-4b1c-ab84-00e4e49ce047.png)

Repository link: https://github.com/aritra-tech/GitCheatFinder

**Comment by aadityamp01** [comment]
Okay, Change your issue title to add app name to it

**Comment by aritra-tech** [comment]
> Okay, Change your issue title to add app name to it

Ok

**Comment by aritra-tech** [comment]
Can you assign it to me @aadityamp01
