### ISSUE TITLE
Adding new Age-Calculator android application

### ISSUE THREAD

**Issue by Suryansh1720001** [aadityamp01/Androapps#101]
# Age-Calculator
Age-Calculator is a kotlin based android application. In this, we can calculate the date, year, minutes, etc with the help of DOB.

# Tech used -
Kotlin language
xml language
Android Studio

**Comment by Suryansh1720001** [comment]
Please @aadityamp01 assign this to me. I want to work on this project.

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!

**Comment by Suryansh1720001** [comment]
Hello @aadityamp01 
Okay after going through the readme.md and contributing file. I send the pull request #109. 
Thank you
