### ISSUE TITLE
RawTemplate

### ISSUE THREAD

**Issue by binayshaw7777** [aadityamp01/Androapps#104]
1. I would like to submit a pre-developed android app (Kotlin) consisting of screens like:
  1. Splash screen
  2. Onboarding Screen
  3. SignUp
  4. SignIn
  5. Forgot Password
  6. Homescreen (with Bottom navigation bar)
This will make the development process easy and will also save a lot of time.

2. Kotlin + XML + Firebase

**Additional context**
@aadityamp01 Please approve. Also, this was a collaborative project where @aritra-tech (https://github.com/aritra-tech) was involved. Can you please assign him too? We both share equal credit to the app.

**Comment by aadityamp01** [comment]
Okay, Assigning to you only, it's a boilerplate code not a new android app, Also rename your app so beginners will understand easily not rawtemplate!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

**Comment by aadityamp01** [comment]
Hey @binayshaw7777 if you're still working on this issue, please update here or it'll be assigned to someone else

**Comment by aadityamp01** [comment]
If anyone wants to take this issue, please comment below!
