### ISSUE TITLE
 Create new androapp  NumberGuessingGame

### ISSUE THREAD

**Issue by atulnarayan16** [aadityamp01/Androapps#106]
**Please describe about your Androapp**
1. It is a number guessing game that asks player to guess the number between 1 to 100. Player is given 10 number of tries, if player guesses the number successfully in less than 10 tries, the player wins else the player loses. 
2. Flutter, Dart.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No  additional context.

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
