### ISSUE TITLE
 Create new androapp  Doctor App

### ISSUE THREAD

**Issue by rik-chatterjee** [aadityamp01/Androapps#107]
**Please describe about your Androapp**
1. It is a app that can be use to make appointment with doctors in your city , doctor can send pdf of prescribtion, doctors can accept appointment, it will have two interfaces 1.Doctor 2.Patient, it uses firebase as backend for storing doctors and patient data.
2. Dart,Flutter, Firebase 

**Describe alternatives you've considered**
No alternatives

**Additional context**
sample of UI
![Onboarding_page](https://user-images.githubusercontent.com/82376158/195307618-b3e94443-f35d-4780-b8d5-3a94f54639a0.jpg)
![Dashboard](https://user-images.githubusercontent.com/82376158/195307642-8ffdd6bb-9610-48e5-9f49-632beb6bd7a8.jpg)

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
