### ISSUE TITLE
 Biometric Authentication

### ISSUE THREAD

**Issue by Esetobore** [aadityamp01/Androapps#112]
**Please describe about your Androapp**
1. A simple and straightforward approach to integrating biometric authentication to your app
2. Kotlin as the programming language 

**Additional context**
Prior authentication issue has been closed and wasn't merged would like to reopen a request

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
