### ISSUE TITLE
Custom Navigation Bar Integration (meow)

### ISSUE THREAD

**Issue by Esetobore** [aadityamp01/Androapps#113]
**Please describe about your Androapp**
1. Creating an app with detailed explanation of the dependencies and work around to creating a custom bottom nav bar 
2. Kotlin as the preferred language

**Comment by aadityamp01** [comment]
Hey @Esetobore 
Please finish your assigned issue, then this issue will be assigned to you!

**Comment by aadityamp01** [comment]
If anyone wants to take this issue, please comment below!
