### ISSUE TITLE
To-do list app 

### ISSUE THREAD

**Issue by Chirantan2** [aadityamp01/Androapps#120]
### To-do App
1. A TO-DO list app using Hive local database
2. Flutter - Dart - Hive 

### Features of the app
1. Create new task
2. Delete the task 
3. Storing the created task on local device

### Alternate Features that can be added 
1. Due date feature for tasks 
2. Search feature for searching previously completed tasks

**Comment by aadityamp01** [comment]
Okay, Go ahead, Make sure to add flutter in your app name to distinguish between kotlin and flutter app in repo

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
