### ISSUE TITLE
 Create new androapp  DialogueBoxes

### ISSUE THREAD

**Issue by jmanan088** [aadityamp01/Androapps#122]
**Please describe about your Androapp**
1. App to display various dialogue boxes using sweetAlertDialog library.
2. JAVA

**Describe alternatives you've considered**
This is an alternative to to creating your own dialogue boxes

**Additional context**

**Comment by jmanan088** [comment]
@aadityamp01 please assign this to me

**Comment by aadityamp01** [comment]
Okay, Go ahead

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
