### ISSUE TITLE
 Create new androapp  WidgetApp

### ISSUE THREAD

**Issue by jmanan088** [aadityamp01/Androapps#126]
**Please describe about your Androapp**
1. An app to create a widget
2. Java

**Describe alternatives you've considered**

**Additional context**

**Comment by jmanan088** [comment]
@aadityamp01 please assign me this. Also if i close this by today will you able to accept this under hacktoberfest?

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!

**Comment by jmanan088** [comment]
@aadityamp01 please review this

**Comment by aadityamp01** [comment]
Hey @jmanan088 it's basic single page app only!
This app won't be considered, if you have another idea you can raised an issue!
