### ISSUE TITLE
Add a Quiz App (beginner friendly)

### ISSUE THREAD

**Issue by akshatbhuhagal** [aadityamp01/Androapps#27]
Create an Quiz app that can take 10 question.
For every question we have to select any one correct answer out of 4 answer.

**Comment by akshatbhuhagal** [comment]
Please assign it to me 👍🏻 
Thanks

**Comment by akshatbhuhagal** [comment]
Already add Pull Request for adding Quiz App check :)

**Comment by aadityamp01** [comment]
Hey @akshatbhuhagal this same app is already exist in my github profile only, We can't spam Github community!!
You can think of another idea about quiz app that will be accepted!

**Comment by akshatbhuhagal** [comment]
Oh sure i can make an new app with fresh app ty for letting me know about these things 
I'm kinda new to open source so yeah
