### ISSUE TITLE
Create an android application using github API

### ISSUE THREAD

**Issue by aadityamp01** [aadityamp01/Androapps#36]
## Description

1. Your app must use Github API
2. You can use any language for android - Java/ kotlin/ flutter
3. You can create beginner friendly application with your own idea, and designs 
4. Please use appropriate comments to self describe your code
5. Add necessary readme.md, images
6. Already existing Github clone apps will consider as spam.

You can comment below to get assigned to this issue.

**Comment by aadityamp01** [comment]
Sure! Go ahead;
Assigning to you!

**Comment by aadityamp01** [comment]
Hey @henrikhorbovyi please update your progress here, so we'll know, you are still working on same issue

**Comment by henrikhorbovyi** [comment]
I'll open a PR soon
