### ISSUE TITLE
Add more android applications to help beginners understand app development

### ISSUE THREAD

**Issue by aadityamp01** [aadityamp01/Androapps#4]
#### Title of an issue

Give related title to an issue or changes you will be fixing in the repository

#### Description

Write short description about your issue

**Comment by sudipbhakat07** [comment]
Hello Aditya, I have added a Notes App and created a pull request. Please merge it.
Thank you in advance!

**Comment by Vaibhav2002** [comment]
> ## Add new helpful and informative apps which will be resourceful to the beginners of android development
> ### Follow this template for Raising an issue
> #### Title of an issue
> Give related title to an issue or changes you will be fixing in the repository
> 
> #### Description
> Write short description about your issue

Can i make a login/register application using firebase, which shows usage of hilt, MVVM,  Kotlin Flows, and some best practices.
@aadityamp01
