### ISSUE TITLE
Create music player android application

### ISSUE THREAD

**Issue by aadityamp01** [aadityamp01/Androapps#42]
## Description

1. You can use add your own features
2. You can use any language for android - Java/ kotlin/ flutter
3. You can create beginner friendly application with your own idea, fancy libraries and designs 
4. Please use appropriate comments to self describe your code
5. Add necessary readme.md, images
6. Already existing apps on github will be considered as spam

You can comment below to get assigned to this issue.

**Comment by Priyanshi-Sharma-142** [comment]
I would like to work on this project using java can u pls assign it to me.

**Comment by Priyanshi-Sharma-142** [comment]
Almost completed. Few modification required. 
Will add it by tomorrow.
