### ISSUE TITLE
Build Any Favourite Franchise List using REST APIs

### ISSUE THREAD

**Issue by rahulsain** [aadityamp01/Androapps#5]
Example: Pokemon app which shows pokemon photo its details evolution , info, etc in card view in recycler view adapter using APIs

**Comment by duttabhishek0** [comment]
Hey, I can work on this. I can build an application using Kotlin. Can you assign it to me?

**Comment by aadityamp01** [comment]
Sure! go ahead!
Assigning to you!

**Comment by aadityamp01** [comment]
Hey @duttabhishek0 please update your progress here, so we'll know you are still working on same issue

**Comment by duttabhishek0** [comment]
Backend part doen, working on the UI.

**Comment by duttabhishek0** [comment]
Hey,
Sorry, but I don;t think so I would be able to complete it on time. Please remove me. I got engaged in some internship work. Again apologies!

**Comment by Kajal13081** [comment]
@aadityamp01 can you assign this issue to me?

**Comment by aadityamp01** [comment]
Hey @Kajal13081 please update your progress here, so we'll know you are still working on same issue
