### ISSUE TITLE
Grocery List Application

### ISSUE THREAD

**Issue by Kajal13081** [aadityamp01/Androapps#50]
I want to create a grocery list application. 
User can add, remove, edit the items in order to minimise the wastage of food. 
This is a beginner level project. 
And I want to do it in java. 
Please assign me @aadityamp01

**Comment by aadityamp01** [comment]
Please try to finish your first assigned issue, then this issue will be assigned to you!

**Comment by aadityamp01** [comment]
Hey @nisarga-kh please update your progress here, so we'll know, you are still working on same issue, or it'll be unassigned!

**Comment by aadityamp01** [comment]
Hey @nisarga-kh I am assuming you are not working on this issue, because you haven't updated!
Removing you from this issue and closing this issue
