### ISSUE TITLE
Retrofit Demo App

### ISSUE THREAD

**Issue by akshatbhuhagal** [aadityamp01/Androapps#52]
In this app we can show that how to use Retrofit for calling API and get data from API.

**Comment by aadityamp01** [comment]
Hey @akshatbhuhagal one folk already sent PR on same issue, and not confirmed anything yet, so after confirmation, will assign this to you;
If you want to contribute, you can try [here](https://github.com/aadityamp01/Androapps/pull/51#issuecomment-942686041) 
send PR directly.
