### ISSUE TITLE
Random Word Shuffler App

### ISSUE THREAD

**Issue by rahulsain** [aadityamp01/Androapps#6]

**Comment by xtanion** [comment]
I'll be working on an app that will jumble the word and display it to the user, if the user is able to find the correct meaningful word then he'll get a point, else he'll lose the point. He may take hints but that may cost him some points.

**Comment by aadityamp01** [comment]
Yes go ahead! 
Assigning to you!

**Comment by xtanion** [comment]
Fixed issue in: 1f5fa41d0736d4ee3489c13da2cd05c24c94a005
