### ISSUE TITLE
Remove hardcoded strings from the apps

### ISSUE THREAD

**Issue by aadityamp01** [aadityamp01/Androapps#7]
To Reproduce

    1. Set up application on your android studio 
    2. Check if it contains any hardcoded strings
    3. Change it by adding into values/strings.xml

Additional context
Make sure to let me know here first so that I can assign this issue to you

**Comment by gouravkhunger** [comment]
Hi! Can you please clarify do you wish to convert the hardcoded strings for all the subprojects in this repo?

**Comment by aadityamp01** [comment]
Yes! You can do that
Make sure you just convert the hardcoded strings. If you want to fix bugs and dependencies please create new issues.

Comment below you want to work on it, I will assign it to you

**Comment by gouravkhunger** [comment]
Sure, I will do it.

**Comment by aadityamp01** [comment]
Okay! 
Go ahead!

**Comment by gouravkhunger** [comment]
Hey check the PR, I have removed the hard-coded strings and made some other needed changes!
