### ISSUE TITLE
Improve Weather App

### ISSUE THREAD

**Issue by hlavu** [aadityamp01/Androapps#72]
**Describe the feature/ bug**
The current weather app just allows users to view weather forecast of one location at a time. I want to update the app so it will have a list of searched locations with some information in another page.

**Screenshots**
The list will somehow look like this.
![image](https://user-images.githubusercontent.com/44437742/140680322-417ffe28-5c3e-476c-bad5-577b4f6decf3.png)

**Additional context**
Here are some step I will do to develop the app:

1. Add new `list` button to navigate to the history page 
2. Save entered city names in an `ArrayList`
3. Design history page 
4. Pass the `ArrayList` to the history page when the `list` button is clicked
5. Retrieve weather information of each city and display them to the list

If you have any suggestion, please let me know!

**Comment by aadityamp01** [comment]
LGTM! Go ahead
Assigning to you!
