### ISSUE TITLE
 Create new Mobile App

### ISSUE THREAD

**Issue by aadityamp01** [aadityamp01/Androapps#74]
**Please describe about your Androapp**
1. A clear and concise description about your application and how it'll help to the beginners in android development. Ex. Contributing Calculator app [...]
2. Programming Language 

**Describe alternatives you've considered**

**Additional context**
If possible add any other context or screenshots about the feature request here.

**Comment by RahulSoni0** [comment]
hey! I want to contribute an app that will contain the all the commonly used **FireBase ML Kit** resources in one single app and i will include documentation for the same if new developers want to follow along just by reading the documentation.

**Comment by aadityamp01** [comment]
Hey Rahul! Thats great!
Can you please create new issue for your app so I'll assign that issue to you, as this is a general issue!

**Comment by jmanan088** [comment]
Hey, I want to contribute an android app to click a photo and add your current latitude and longitude on top the photo as text and download that photo in phone.

**Comment by mufida1018** [comment]
Hey,
I would like to contribute an app that shows climate.
It will help new beginners to work with API as well as have hands-on UI part.
I would use Flutter.
