### ISSUE TITLE
Biometric Authentication App

### ISSUE THREAD

**Issue by utkarsh006** [aadityamp01/Androapps#75]
**Please describe your Androapp**
This android app provides a way to verify, beyond a doubt, that a person is who they say they are. Biometric authentication performs this verification by checking distinctive biological or behavioral characteristics.

**Describe alternatives you've considered**
No alternatives are present.

**Additional context**
No Context for the time being

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1. Please go through README.md and CONTRIBUTING.md
2. Already existing apps on github will be considered as spam, try to make your own UI
3. Please use appropriate comments to self describe your code
4. Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
