### ISSUE TITLE
 Create new android app  Image To Text Using ML Kit

### ISSUE THREAD

**Issue by RahulSoni0** [aadityamp01/Androapps#76]
**Please describe about your Android app**
1. Android app demo of Implementation of FireBase ML Kit , will implement Image to text function to scan any image and extract the textual contains from it, works for both handwritten and typed texts
2. JAVA , XML

**Comment by RahulSoni0** [comment]
@aadityamp01

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:


1. Please go through README.md and CONTRIBUTING.md
2. Already existing apps on github will be considered as spam, try to make your own UI
3. Please use appropriate comments to self describe your code
4. Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.


Assigning to you!
