### ISSUE TITLE
Calculator app has cheap UI

### ISSUE THREAD

**Issue by gani2267** [aadityamp01/Androapps#78]
**Describe the feature/ bug**
Calculator app here is only present in native. Not in flutter also the UI is poor.

![calc_ss1](https://user-images.githubusercontent.com/84265879/193428213-fe351ca5-9a96-4faf-9557-27be77a61338.jpg)

**Comment by akashdnb** [comment]
Hey I would like to work on this issue

**Comment by gani2267** [comment]
Yes I have created a PR which have code of calculator app in flutter who's UI is awesome and neumorphism effect is used in its ui

**Comment by aadityamp01** [comment]
Hello @gani2267 
Make proper description of your issue, if you're adding new mobile app, don't compare it with already added apps, make sure you follow proper guidelines of hacktoberfest 2022.
After assignment of issue, you can open PR and link it with your issue
Thank you!
