### ISSUE TITLE
 Create new Flutter Increment Number App

### ISSUE THREAD

**Issue by axatabyss** [aadityamp01/Androapps#80]
**About Flutter App**
1. It's a Flutter based application which help's user's to understand basic concepts of Flutter with two buttons where 1st button will increase number and 2nd button will decrease number.
2. Using Flutter (Dart)

**Comment by axatabyss** [comment]
Assign this issue to me 
Thanks

**Comment by krishna-raz** [comment]
can i work this app

**Comment by axatabyss** [comment]
@aadityamp01 request you to Assign this issue to me as hacktoberfest label

**Comment by aadityamp01** [comment]
Hey @axatabyss 
Flutter application you're referring is a default application generates when we create a new project, this app won't be considered in this poject! If you have another idea feel free to raise a new issue
Thank you!

**Comment by axatabyss** [comment]
Not a default I'm going to build it in Bloc architecture to explain the basic knowledge of how Bloc architecture work's in flutter

**Comment by elysian12** [comment]
@axatabyss can you please assign me this issue
