### ISSUE TITLE
 Create new Click Counter Android App

### ISSUE THREAD

**Issue by satyacasm** [aadityamp01/Androapps#82]
**Please describe about your Androapp**
1. A Click Counter app stores the no. of times a user clicks on the button. It has a reset functionality too.
2. Kotlin
.

**Additional context**
<img width="145" alt="image" src="https://user-images.githubusercontent.com/98680993/193436619-4be52f5d-bd25-4900-b485-467c55f4bd4d.png">

@aadityamp01 request you to assign this issue to me.

**Comment by gani2267** [comment]
Hello flutter similar type of app is given defaulty when we create project. I think that creating such very basic app is not a good idea.

**Comment by aadityamp01** [comment]
Hey @satyacasm 
Your application is good but we've already added, apps in kotlin which uses these concepts of android.
If you have more ideas, feel free to raise a new issue, will assign it to you!
Thank you!
