### ISSUE TITLE
PictureClickingApp

### ISSUE THREAD

**Issue by jmanan088** [aadityamp01/Androapps#84]
**Please describe about your Androapp**
1.  An app to click a photo and set it to image view and allow user to download that to phone gallery.
2.  Java

**Describe alternatives you've considered**
No Alternatives

**Additional context**
No additional context.

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.  Please go through README.md and CONTRIBUTING.md
2.  Already existing apps on github will be considered as spam, try to make your own UI
3.  Please use appropriate comments to self describe your code
4.  Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!

**Comment by neil0504** [comment]
Hello @aadityamp01, if no one is working on this issue, I would like to work on it.

**Comment by jmanan088** [comment]
Hello, I'm already working on the issue.
