### ISSUE TITLE
I would like to add few android roadmaps and resources in readme file

### ISSUE THREAD

**Issue by Shubhcs01** [aadityamp01/Androapps#86]
**Describe the solution you'd like**
I will add few more Android Roadmaps with free resources to study.
Also, will  update the hacktoberfest 2022 official link.

**Comment by Shubhcs01** [comment]
could you please assign me this issue under hacktoberfest.

**Comment by aadityamp01** [comment]
Hey @Shubhcs01  
Yes  with this, Is it possible for you to make a new organized readme file to keep only resources and you can link that into main readme, in a good format, it'll be great help, also if have more doubts on this please ask here!

**Comment by Shubhcs01** [comment]
okay, not an issue @aadityamp01 , I will do that 👍

**Comment by aadityamp01** [comment]
Okay, Go ahead!
Assigning  to you!

**Comment by Shubhcs01** [comment]
@aadityamp01 Is this PR right?
