### ISSUE TITLE
 Create new androapp  Movies

### ISSUE THREAD

**Issue by Simran1604** [aadityamp01/Androapps#87]
**Please describe about your Androapp**
1. A Flutter app that has list of movies and its details along with its trailer and posters.
2. Dart 

**Describe alternatives you've considered**
No alternatives
**Additional context**
https://user-images.githubusercontent.com/72657303/193506848-c4e69751-1d46-4011-a8b6-3e03762c3b79.mp4

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.  Please go through README.md and CONTRIBUTING.md
2.  Already existing apps on github will be considered as spam, try to make your own UI
3.  Please use appropriate comments to self describe your code
4.  Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!

**Comment by aadityamp01** [comment]
Hey @Simran1604 if you're still working on this issue, please update here or it'll be assigned to someone else

**Comment by aadityamp01** [comment]
If anyone wants to take this issue, please comment below!

**Comment by aadityamp01** [comment]
Closing this issue!
