### ISSUE TITLE
 Create new App in Bloc Architecture

### ISSUE THREAD

**Issue by axatabyss** [aadityamp01/Androapps#93]
About Flutter App

1. Flutter Default Click Counter using BLoC architecture.
2. It's a Flutter based application which help's user's to understand basic concepts of Flutter with two buttons where 1st button will increase number and 2nd button will decrease number Using Flutter (Dart)

**Comment by aadityamp01** [comment]
Hey @axatabyss 
Flutter application you're referring with BLoC architecture is already available on github itself, If you have another idea  with Bloc architecture feel free to discuss here
Thank you!
