### ISSUE TITLE
Calculator app does not have backspace button

### ISSUE THREAD

**Issue by akashdnb** [aadityamp01/Androapps#95]
**The Calculator App should have a backspace button**
It should delete the last entered digit from the textview.
If a user enters a wrong digit, he/she will have to clear all the digits inspite of the last digit.

**Add a backspace button**
which will delete the last entered digit which will be convenient for users.

**The backspace button will look like as shown in the following screenshot**

<p align= "centre" >
<img src="https://user-images.githubusercontent.com/85953406/194370205-eb95e50e-74ba-40d1-bcea-bb1b8c570e87.jpg" width="200" height="380"  >
</p>

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
