### ISSUE TITLE
 Create new androapp  Tic_Tac_Toe

### ISSUE THREAD

**Issue by RohitLakra299** [aadityamp01/Androapps#96]
**Please describe about your Androapp**
1.  A simple tic_tac_toe game, having multiplayer and singleplayer mode.
     We can login via google and store stats in singleplayer mode with the help of firebase authentication and firestore.
     Beginners will learn about ViewModels, Firebase, Landscape layouts etc. 
2. Kotlin

**Describe alternatives you've considered**
No alternatives

**Additional context**
**ScreenShots**
<div style="display:flex;flex-wrap:wrap;">
<img src="https://user-images.githubusercontent.com/78154259/193349759-2250a094-591c-423f-b79e-6aff48d7acaf.jpeg" width="300px" height="620px" />
<img src="https://user-images.githubusercontent.com/78154259/193349788-c11bc6fa-617b-40a6-b5d7-aeac675b0b64.jpeg" width="300px" height="620px" />
<img src="https://user-images.githubusercontent.com/78154259/193350016-9e2d3049-587f-40a8-add8-b3135ccc883a.jpeg" width="300px" height="620px" />
<img src="https://user-images.githubusercontent.com/78154259/193350024-cbe9c6bd-6fb0-4771-bc1d-7659f3e855d6.jpeg" width="300px" height="620px" />
</div>

**Comment by aadityamp01** [comment]
Okay, Go ahead!

Please Note:

1.   Please go through README.md and CONTRIBUTING.md
2.   Already existing apps on github will be considered as spam, try to make your own UI
3.   Please use appropriate comments to self describe your code
4.   Add necessary readme.md - references of your learnings and dependencies, images (screenshots); refer latest added apps for this task.

Assigning to you!
