### ISSUE TITLE
Update Calculator app compileSdk/targetSdk version to latest

### ISSUE THREAD

**Issue by AnAndroidOne** [aadityamp01/Androapps#98]
**Describe the feature/ bug**
Update Calculator app compileSdk/targetSdk version to 33 as its recommended to use the latest version

**To Reproduce issue or location of your feature**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aadityamp01** [comment]
Hey! It's basic app so version migration is not necessary, app is working fine!
Feel free to raise a new issue if you have project ideas or want to add new feature into app
Thank you!
